### PR TITLE
Update clipboard-win to 4.2.1

### PR DESCRIPTION
**Pull request by stevanmilic**
By updating the clipboard-win we resolve the issue #9.

Also some of the code has been simplified, since new clipboard-win
version has simplified API.

### CODE REVIEW

**Comment by stevanmilic** [comment]
@equalsraf I've made some improvements that resolves the #9 issue, can you please check the code?

**Comment by SamSaffron** [comment]
Confirming this fixed #9 for me 🎊 🎊 🎊 

Thank you @stevanmilic !

**Comment by equalsraf** [comment]
I am seeing a test failure for this where the clipboard is not set

https://ci.appveyor.com/project/equalsraf/win32yank/builds/42380293/job/36qim4mhletcn4ob

**Comment by elevin72** [comment]
> I am seeing a test failure for this where the clipboard is not set
> 
> https://ci.appveyor.com/project/equalsraf/win32yank/builds/42380293/job/36qim4mhletcn4ob

Here's an odd question. In actual use is it possible to copy an empty string? I understand that the test isn't passing. My understanding is that if you give set_clipboard() an empty string it just won't actually do the set. (See https://github.com/DoumanAsh/clipboard-win/blob/02a16b5dfc92cf7f8897c4aaa4e8e56fab883326/src/raw.rs#L281)
But where in actual use cases is it possible to copy an empty string?

**Comment by equalsraf** [comment]
Closing, merged #16

**Pull request closed without merging**
